=== jmshelby/ffencoderd/doc/ffencoderd.dtd
<!-- This is the schema for the 3 types of XML files that ffencoderd interacts with
Video file : this will be mainly a file which ffencoderd uses as output to stat already done processes.
Processes files : these are files which may be found in the process dir, define a process with at least profile and file tags.
Profiles file : this schema defines structure of the profiles file, which is used to define which profiles (ffmpeg options) may be defined in processes.-->

<!--Root element-->
<!ELEMENT ffencoderd (video*|process*|profile*) >

<!-- Schema for the output file -->
<!--Video : This is the container for the codified videos-->
<!ELEMENT video (description?,size?,format?,filename?) >
<!-- Defines a unique identifier for this resource-->
<!ATTLIST video source CDATA #REQUIRED>
<!-- This is the identifier from a process(see Process schema) -->
<!ATTLIST video id ID #REQUIRED>
<!-- Containes a brief description for the resource-->
<!ELEMENT description (#PCDATA) >
<!-- Contains the format for the resource -->
<!ELEMENT format (#PCDATA) >
<!-- Contains the original name for the resource -->
<!ELEMENT filename (#PCDATA) >

<!-- Process schema -->
<!--Process : element containing encoding process definition for a file -->
<!ELEMENT process (file,parameter?)>
<!-- Unique identifier used for external control, it's not really needed to be an ID-->
<!ATTLIST process id ID #REQUIRED>
<!-- Profile name to use for this process -->
<!ATTLIST process profile CDATA #REQUIRED>
<!-- filename to encode, found in the input dir -->
<!ELEMENT file (#PCDATA)>
<!-- Parameter data will only be used to define process parameter values at posting time -->
<!ELEMENT parameter (#PCDATA) >

<!-- Profile Schema -->
<!-- Parameters will be parsed in order of appearence -->
<!-- Profile : element containing encoding definition, think of them as templates-->
<!ELEMENT profile (infile?,outfile?)>
<!-- Profile's name -->
<!ATTLIST profile name ID #REQUIRED>
<!-- Profile's mount point, path where resources encoded with this profile will be accessible -->
<!ATTLIST profile mount CDATA "">
<!-- Media type, use mime valid media type -->
<!ATTLIST profile type CDATA "">
<!-- Extension, see it matches to the one that ffmpeg produces -->
<!ATTLIST profile ext CDATA "">
<!-- Parameters passed to input file -->
<!ELEMENT infile (parameter*)>
<!-- Parameters passed to output file -->
<!ELEMENT outfile (parameter*)>
<!-- Parameter name, this is used to reference it in the process definition from the input. If the parameter name is empty this will be passed to the run command directly with the default value -->
<!ATTLIST parameter name CDATA #REQUIRED>
<!-- Argument that will be passed to run the command with the value from the process definition -->
<!ATTLIST parameter arg CDATA "">
<!-- Default value for the defined parameter argument, if empty empty string will be used, if not defined the argument wont be setted if there's not a defined value in process definition -->
<!ATTLIST parameter default CDATA "">

=== jmshelby/ffencoderd/data/profiles.xml
<?xml version="1.0"?>
<!DOCTYPE ffencoderd SYSTEM "ffencoderd.dtd">
<ffencoderd>
<!-- A profile definition needs the following attributes
	name : is used as an identifier for internal use 
	mount : mount point on the server, will be used to determine the path served through HTTP
	type : is the content type used for files served from this mount point see http://www.iana.org/assignments/media-types/ (optional)
	-->
	<profile name="default" mount="video.flv" type="video/x-flv" ext="flv">
	<!-- Outfile parameters, these are arguments used for the output file-->
		<outfile>
			<parameter arg="-f" name="format" default="flv"></parameter>
			<!-- If a parameter has an empty name it will be allways defined with the value of the default attribute -->
			<parameter arg="-y" name="overwrite"></parameter>
			<parameter arg="-acodec" name="audiocodec"></parameter>
			<parameter arg="-ar" name="audiorate" default="22050"></parameter>
			<parameter arg="-s" name="size" default="320x240"></parameter>
			<parameter arg="-aspect" name="aspect" default="4:3"></parameter>
			<parameter arg="-ab" name="audiobitrate" default="56"></parameter>	
			<parameter arg="-r" name="rate" default="15"></parameter>	
			<parameter arg="-ac" name="audiochannel" default="1"></parameter>	
			<!-- If a parameter hasn't a default attribute defined it won't be setted unless the process defintion defines a value -->
			<parameter arg="-b" name="bitrate"></parameter>									
		</outfile>
	</profile>
	<profile name="thumbnail" mount="thumbnail.jpg" type="image/jpeg" ext="jpg">
		<outfile>
			<parameter arg="-f" name="format" default="mjpeg"></parameter>
			<!-- Overwrite output file -->
			<parameter arg="-y" name="overwrite" default=""></parameter>
			<parameter arg="-ss" name="time" default="0"></parameter>
			<parameter arg="-s" name="size" default="220x120"></parameter>
			<parameter arg="-vframes" name="" default="1"></parameter>
			<parameter arg="-an" name="noaudio" default=""></parameter>							
		</outfile>
	</profile>
	<profile name="h263" mount="h263.avi" type="video/x-h263" ext="avi">
		<outfile>
			<parameter arg="-f" name="format" default="h263"></parameter>
			<parameter arg="-s" name="size" default="352x288"></parameter>						
		</outfile>
	</profile>
</ffencoderd>

=== jmshelby/ffencoderd/doc/profiles.xml
<?xml version="1.0"?>
<!DOCTYPE ffencoderd SYSTEM "ffencoderd.dtd">
<ffencoderd>
<!-- A profile definition needs the following attributes
	name : is used as an identifier for internal use 
	mount : mount point on the server, will be used to determine the path served through HTTP
	type : is the content type used for files served from this mount point
	-->
	<profile name="default" mountpoint="video.flv" type="video/x-flv">
	<!-- Infile parameters, these are used to define input arguments for the input file -->
		<infile></infile>
	<!-- Outfile parameters, these are arguments used for the output file-->
		<outfile>
			<parameter arg="-f" name="format" default="flv"></parameter>
			<!-- If a parameter has an empty name it will be allways defined with the value of the default attribute -->
			<parameter arg="-y" name="" default=""></parameter>
			<parameter arg="-acodec" name="audiocodec" default="mp3"></parameter>
			<parameter arg="-ar" name="audiorate" default="22050"></parameter>
			<parameter arg="-s" name="size" default="320x240"></parameter>
			<parameter arg="-aspect" name="aspect" default="4:3"></parameter>
			<parameter arg="-ab" name="audiobitrate" default="56"></parameter>	
			<parameter arg="-r" name="rate" default="15"></parameter>	
			<parameter arg="-ac" name="audiochannel" default="1"></parameter>	
			<!-- If a parameter hasn't a default attribute defined it won't be setted unless the process defintion defines a value -->
			<parameter arg="-b" name="bitrate"></parameter>									
		</outfile>
	</profile>
	<profile name="thumbnail" mountpoint="thumbnail.jpg" type="video/x-flv">
		<outfile>
			<parameter arg="-f" name="format" default="mjpeg"></parameter>
			<!-- Overwrite output file -->
			<parameter arg="-y" name="" default=""></parameter>
			<parameter arg="-ss" name="time" default="0"></parameter>
			<parameter arg="-s" name="size" default="220x120"></parameter>
			<parameter arg="-vframes" name="" default="1"></parameter>
			<parameter arg="-an" name="" default=""></parameter>							
		</outfile>
	</profile>
</ffencoderd>
